baseURL = "https://blog.n4o.xyz"
defaultContentLanguage = "id"
languageCode = "id"
theme = "uBlogger"

title = "N4O Blog"
enableRobotsTXT = true
enableGitInfo = true
enableEmoji = true

[languages]
    [languages.id]
        weight = 1
        languageCode = "id"
        languageName = "Indonesia"
        hasCJKLanguage = false
        paginate = 10

        [languages.id.menu]
            [[languages.id.menu.main]]
                identifier = "posts"
                name = "Postingan"
                url = "posts/"
                title = "Postingan"
                weight = 1
            [[languages.id.menu.main]]
                identifier = "tags"
                name = "Tagar"
                url = "tags/"
                title = "Tagar"
                weight = 2
            [[languages.id.menu.main]]
                identifier = "about"
                name = "Tentang"
                url = "about/"
                title = "Tentang"
                weight = 3
            [[languages.id.menu.main]]
                identifier = ""
                name = "Rilisan"
                url = "https://shigoto.n4o.xyz/"
                title = "Rilisan"
                weight = 4
        [languages.id.params.home]
            rss = 10
            [languages.id.params.home.profile]
                enable = true
                gravatarEmail = "noaione0809@gmail.com"
                avatarURL = "/images/avatar.png"
                title = "N4O Blog"
                subtitle = "Seseorang yang<s> melakukan fansubbing</s> jatuh ke Neraka VTuber."
                social = true
                disclaimer = ""
            [languages.id.params.home.posts]
                enable = true
                paginate = 10
        [languages.id.params.social]
            GitHub = "noaione"
            Twitter = "nao0809_"
            Email = "noaione0809@gmail.com"
            Steam = "N4O"
            RSS = true
            Trakteer = "noaione"

    [languages.en]
        weight = 2
        languageCode = "en"
        languageName = "English"
        hasCJKLanguage = false
        paginate = 10

        [languages.en.menu]
            [[languages.en.menu.main]]
                identifier = "posts"
                name = "Posts"
                url = "posts/"
                title = "Posts"
                weight = 1
            [[languages.en.menu.main]]
                identifier = "tags"
                name = "Tags"
                url = "tags/"
                title = "Tags"
                weight = 2
            [[languages.en.menu.main]]
                identifier = "about"
                name = "About"
                url = "about/"
                title = "About"
                weight = 3
            [[languages.en.menu.main]]
                identifier = ""
                name = "Release"
                url = "https://shigoto.n4o.xyz/"
                title = "Release"
                weight = 4
        [languages.en.params.home]
            # amount of RSS pages
            rss = 10
            # Home page profile
            [languages.en.params.home.profile]
                enable = true
                gravatarEmail = "noaione0809@gmail.com"
                avatarURL = "/images/avatar.png"
                title = "N4O Blog"
                subtitle = "Simple guy <s>doing fansubbing works</s> stuck in VTubers hell."
                typeit = true
                social = true
                disclaimer = ""
            [languages.en.params.home.posts]
                enable = true
                paginate = 10
        [languages.en.params.social]
            GitHub = "noaione"
            Twitter = "nao0809_"
            Email = "noaione0809@gmail.com"
            Steam = "N4O"
            RSS = true
            Trakteer = "noaione"

[params]
    version = "2.0.X"
    defaultTheme = "dark"
    gitRepo = "https://github.com/noaione/n4o-blog-web"
    images = ["/assets/logo.png"]
    title = "N4O Blog"
    description = "Simple guy ~~doing fansubbing works~~ stuck in VTubers hell."
    enableRobotsTXT = true
    enableGitInfo = true
    enableEmoji = true
    [params.analytics]
        enable = true
        [params.analytics.google]
            id = "UA-90117853-1"
            anonymizeIP = true
    [params.page.share]
        enable = false
    [params.page.code]
        copy = true
    [params.comment]
        enable = true
        [params.comment.disqus]
            enable = true
            shortname = "n4oblog"
    [params.footer]
        enable = true
        custom = "Blog designed with <a href='https://github.com/noaione/uBlogger'>modified uBlogger theme</a><br>Every post here is written personally by N4O<br>"
        hugo = false
        copyright = true
        author = true
        since = 2019
    [params.search]
        enable = true
        type = "lunr"
        contentLength = 4000
        maxResultLength = 10
        snippetLength = 30
        highlightTag = "em"
        absoluteURL = false
[author]
    name = "n4o.en"

[markup]
    [markup.highlight]
        codeFences = true
        guessSyntax = true
        lineNos = true
        lineNumbersInTable = true
        noClasses = false
    [markup.goldmark]
        [markup.goldmark.extensions]
            definitionList = true
            footnote = true
            linkify = true
            strikethrough = true
            table = true
            taskList = true
            typographer = true
        [markup.goldmark.renderer]
            unsafe = true
    [markup.tableOfContents]
        startLevel = 2
        endLevel = 6

[privacy]
    [privacy.googleAnalytics]
        anonymizeIP = true
        disable = false

[outputs]
    home = ["HTML", "RSS", "JSON"]
