[build]
publish = "public"
command = "hugo --gc --minify --enableGitInfo -d ./public/blog"

[context.production.environment]
HUGO_VERSION = "0.80.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"