backend:
  name: git-gateway
  repo: noaione/n4o-blog-web
  branch: master # Branch to update (optional; defaults to master)
media_folder: static/assets/img
public_folder: /assets/img
publish_mode: editorial_workflow
site_url: https://blog.n4o.xyz/blog
i18n:
  structure: multiple_files
  locales: [id, en]
collections:
  - name: 'blog'
    label: 'Postingan Baru'
    folder: 'content/posts'
    create: true
    slug: '{{slug}}/index.{{locale}}{{extension}}'
    editor:
      preview: false
    i18n: true
    fields:
      - label: Judul
        name: title
        widget: string
        i18n: translate
      - label: 'Tanggal Publikasi'
        name: date
        widget: datetime
        i18n: duplicate
      - label: 'Update Publikasi'
        name: lastmod
        widget: datetime
        i18n: duplicate
      - label: Deskripsi
        name: description
        widget: string
        required: false
        i18n: translate
      - label: Tagline
        name: subtitle
        widget: string
        required: false
        i18n: translate
      - label: Tagar
        name: tags
        widget: list
        i18n: true
        required: false
      - label: Kategori
        name: categories
        widget: list
        i18n: true
        required: false
      - label: Gambar
        name: featuredImage
        widget: image
        required: false
        i18n: duplicate
      - label: Isi
        name: body
        widget: markdown
        i18n: translate
      - label: lightgallery
        name: lightgallery
        widget: hidden
        default: true
        i18n: duplicate
