backend:
  name: github
  repo: noaione/n4o-blog-web
  branch: master # Branch to update (optional; defaults to master)
media_folder: static/assets/img
public_folder: /assets/img
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    slug: '{{slug}}/index.en.{{extension}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: "Tagline", name: "subtitle", widget: "string" }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: "Featured Image", name: "featuredImage", widget: "image" }
      - { label: "Tags", name: "tags", widget: "list"}
